var orgs = [
{
"login": "zeromq",
"id": 109777,
"url": "https://api.github.com/orgs/zeromq",
"repos_url": "https://api.github.com/orgs/zeromq/repos",
"events_url": "https://api.github.com/orgs/zeromq/events",
"members_url": "https://api.github.com/orgs/zeromq/members{/member}",
"public_members_url": "https://api.github.com/orgs/zeromq/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/109777?v=3",
"description": null
},
{
"login": "LearnBoost",
"id": 204174,
"url": "https://api.github.com/orgs/LearnBoost",
"repos_url": "https://api.github.com/orgs/LearnBoost/repos",
"events_url": "https://api.github.com/orgs/LearnBoost/events",
"members_url": "https://api.github.com/orgs/LearnBoost/members{/member}",
"public_members_url": "https://api.github.com/orgs/LearnBoost/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/204174?v=3",
"description": null
},
{
"login": "senchalabs",
"id": 313839,
"url": "https://api.github.com/orgs/senchalabs",
"repos_url": "https://api.github.com/orgs/senchalabs/repos",
"events_url": "https://api.github.com/orgs/senchalabs/events",
"members_url": "https://api.github.com/orgs/senchalabs/members{/member}",
"public_members_url": "https://api.github.com/orgs/senchalabs/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/313839?v=3",
"description": ""
},
{
"login": "segmentio",
"id": 819518,
"url": "https://api.github.com/orgs/segmentio",
"repos_url": "https://api.github.com/orgs/segmentio/repos",
"events_url": "https://api.github.com/orgs/segmentio/events",
"members_url": "https://api.github.com/orgs/segmentio/members{/member}",
"public_members_url": "https://api.github.com/orgs/segmentio/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/819518?v=3",
"description": ""
},
{
"login": "luna",
"id": 1493601,
"url": "https://api.github.com/orgs/luna",
"repos_url": "https://api.github.com/orgs/luna/repos",
"events_url": "https://api.github.com/orgs/luna/events",
"members_url": "https://api.github.com/orgs/luna/members{/member}",
"public_members_url": "https://api.github.com/orgs/luna/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/1493601?v=3",
"description": null
},
{
"login": "component",
"id": 1687071,
"url": "https://api.github.com/orgs/component",
"repos_url": "https://api.github.com/orgs/component/repos",
"events_url": "https://api.github.com/orgs/component/events",
"members_url": "https://api.github.com/orgs/component/members{/member}",
"public_members_url": "https://api.github.com/orgs/component/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/1687071?v=3",
"description": "modular components for component"
},
{
"login": "basijeGithub",
"id": 4106647,
"url": "https://api.github.com/orgs/basijeGithub",
"repos_url": "https://api.github.com/orgs/basijeGithub/repos",
"events_url": "https://api.github.com/orgs/basijeGithub/events",
"members_url": "https://api.github.com/orgs/basijeGithub/members{/member}",
"public_members_url": "https://api.github.com/orgs/basijeGithub/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/4106647?v=3",
"description": null
},
{
"login": "solid",
"id": 4202963,
"url": "https://api.github.com/orgs/solid",
"repos_url": "https://api.github.com/orgs/solid/repos",
"events_url": "https://api.github.com/orgs/solid/events",
"members_url": "https://api.github.com/orgs/solid/members{/member}",
"public_members_url": "https://api.github.com/orgs/solid/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/4202963?v=3",
"description": null
},
{
"login": "koajs",
"id": 5055057,
"url": "https://api.github.com/orgs/koajs",
"repos_url": "https://api.github.com/orgs/koajs/repos",
"events_url": "https://api.github.com/orgs/koajs/events",
"members_url": "https://api.github.com/orgs/koajs/members{/member}",
"public_members_url": "https://api.github.com/orgs/koajs/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/5055057?v=3",
"description": "Next generation web framework for Node.js"
},
{
"login": "slate",
"id": 5479637,
"url": "https://api.github.com/orgs/slate",
"repos_url": "https://api.github.com/orgs/slate/repos",
"events_url": "https://api.github.com/orgs/slate/events",
"members_url": "https://api.github.com/orgs/slate/members{/member}",
"public_members_url": "https://api.github.com/orgs/slate/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/5479637?v=3",
"description": null
},
{
"login": "clibs",
"id": 5657447,
"url": "https://api.github.com/orgs/clibs",
"repos_url": "https://api.github.com/orgs/clibs/repos",
"events_url": "https://api.github.com/orgs/clibs/events",
"members_url": "https://api.github.com/orgs/clibs/members{/member}",
"public_members_url": "https://api.github.com/orgs/clibs/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/5657447?v=3",
"description": "Package manager for the C programming language along with some packages."
},
{
"login": "reworkcss",
"id": 5658224,
"url": "https://api.github.com/orgs/reworkcss",
"repos_url": "https://api.github.com/orgs/reworkcss/repos",
"events_url": "https://api.github.com/orgs/reworkcss/events",
"members_url": "https://api.github.com/orgs/reworkcss/members{/member}",
"public_members_url": "https://api.github.com/orgs/reworkcss/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/5658224?v=3",
"description": ""
},
{
"login": "expressjs",
"id": 5658226,
"url": "https://api.github.com/orgs/expressjs",
"repos_url": "https://api.github.com/orgs/expressjs/repos",
"events_url": "https://api.github.com/orgs/expressjs/events",
"members_url": "https://api.github.com/orgs/expressjs/members{/member}",
"public_members_url": "https://api.github.com/orgs/expressjs/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/5658226?v=3",
"description": "Organization for HTTP utilities and anything Connect/Express related. Share the maintenance burden! "
},
{
"login": "dropblocks",
"id": 5873421,
"url": "https://api.github.com/orgs/dropblocks",
"repos_url": "https://api.github.com/orgs/dropblocks/repos",
"events_url": "https://api.github.com/orgs/dropblocks/events",
"members_url": "https://api.github.com/orgs/dropblocks/members{/member}",
"public_members_url": "https://api.github.com/orgs/dropblocks/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/5873421?v=3",
"description": null
},
{
"login": "cojs",
"id": 6047096,
"url": "https://api.github.com/orgs/cojs",
"repos_url": "https://api.github.com/orgs/cojs/repos",
"events_url": "https://api.github.com/orgs/cojs/events",
"members_url": "https://api.github.com/orgs/cojs/members{/member}",
"public_members_url": "https://api.github.com/orgs/cojs/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/6047096?v=3",
"description": null
},
{
"login": "uv",
"id": 6080123,
"url": "https://api.github.com/orgs/uv",
"repos_url": "https://api.github.com/orgs/uv/repos",
"events_url": "https://api.github.com/orgs/uv/events",
"members_url": "https://api.github.com/orgs/uv/members{/member}",
"public_members_url": "https://api.github.com/orgs/uv/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/6080123?v=3",
"description": null
},
{
"login": "nanodb",
"id": 6482465,
"url": "https://api.github.com/orgs/nanodb",
"repos_url": "https://api.github.com/orgs/nanodb/repos",
"events_url": "https://api.github.com/orgs/nanodb/events",
"members_url": "https://api.github.com/orgs/nanodb/members{/member}",
"public_members_url": "https://api.github.com/orgs/nanodb/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/6482465?v=3",
"description": null
},
{
"login": "jstrace",
"id": 6807372,
"url": "https://api.github.com/orgs/jstrace",
"repos_url": "https://api.github.com/orgs/jstrace/repos",
"events_url": "https://api.github.com/orgs/jstrace/events",
"members_url": "https://api.github.com/orgs/jstrace/members{/member}",
"public_members_url": "https://api.github.com/orgs/jstrace/public_members{/member}",
"avatar_url": "https://avatars.githubusercontent.com/u/6807372?v=3",
"description": null
}
];
