var user = {
"login": "bholben",
"id": 4744788,
"avatar_url": "https://avatars.githubusercontent.com/u/4744788?v=3",
"gravatar_id": "",
"url": "https://api.github.com/users/bholben",
"html_url": "https://github.com/bholben",
"followers_url": "https://api.github.com/users/bholben/followers",
"following_url": "https://api.github.com/users/bholben/following{/other_user}",
"gists_url": "https://api.github.com/users/bholben/gists{/gist_id}",
"starred_url": "https://api.github.com/users/bholben/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/bholben/subscriptions",
"organizations_url": "https://api.github.com/users/bholben/orgs",
"repos_url": "https://api.github.com/users/bholben/repos",
"events_url": "https://api.github.com/users/bholben/events{/privacy}",
"received_events_url": "https://api.github.com/users/bholben/received_events",
"type": "User",
"site_admin": false,
"name": "Bob Holben",
"company": "HyperGenius",
"blog": "",
"location": "Atlanta",
"email": "bholben@gmail.com",
"hireable": true,
"bio": null,
"public_repos": 39,
"public_gists": 1,
"followers": 3,
"following": 17,
"created_at": "2013-06-20T04:18:24Z",
"updated_at": "2015-01-26T15:26:42Z"
};
